export const LOAD_REPOSITORIES_SUCCESS = 'LOAD_REPOSITORIES_SUCCESS';
export const LOAD_REPOSITORIES_FAILED = 'LOAD_REPOSITORIES_FAILED';
export const LOAD_REPOSITORIES_REQUEST = 'LOAD_REPOSITORIES_REQUEST';

export const LOAD_REPOSITORY_CONTRIBUTORS_SUCCESS = 'LOAD_REPOSITORY_CONTRIBUTORS_SUCCESS';
export const LOAD_REPOSITORY_CONTRIBUTORS_FAILED = 'LOAD_REPOSITORY_CONTRIBUTORS_FAILED';
export const LOAD_REPOSITORY_CONTRIBUTORS_REQUEST = 'LOAD_REPOSITORY_CONTRIBUTORS_REQUEST';

export const loadRepositories = (name) => ({ type: LOAD_REPOSITORIES_REQUEST, name });
export const loadContributors = (name) => ({ type: LOAD_REPOSITORY_CONTRIBUTORS_REQUEST, name });